title: 七七
description: 个人博客
site_title: '@abhn - Abhishek Nagekar'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: qiqi
blog_url: https://suifqi.github.io/qiqi/
email: aign213@foxmail.com
keybase_username: qiqi
twitter_username: qiqi
reddit_username: qiqi

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
